string_utils.h: OK!
string_utils_2.c: OK!
prompt.c: OK!
string_utils_5.c: OK!
string_utils.c: OK!
string_utils_4.c: OK!
string_utils_3.c: OK!
parsing_pass2/parsing_p_p_par.c: OK!
parsing_pass2/parsing_p_p_token.c: OK!
parsing_pass2/parsing_pass2.h: OK!
parsing_pass1/parsing_p_par.c: OK!
parsing_pass1/parsing_p_quotes.c: OK!
parsing_pass1/parsing_p1.c: OK!
parsing_pass1/parsing_p_quotes_2.c: OK!
parsing_pass1/parsing_p_symbol.c: OK!
parsing_pass1/parsing_p_quotes3.c: OK!
parsing_pass1/parsing_pass1.h: OK!
parsing_pass1/parsing_p_str_to_struct.c: OK!
parsing_pass1/parsing_p.c: OK!
